# nginx.yml
- hosts: localhost
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      # For CentOS/RHEL systems, use `yum` instead:
      # yum:
      #   name: nginx
      #   state: present

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
